# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterName', models.CharField(max_length=250, verbose_name='Раздел')),
                ('chapterLogo', models.ImageField(blank=True, null=True, upload_to='exam/images/chapterLogos', verbose_name='Иконка')),
            ],
            options={
                'verbose_name_plural': 'Разделы',
                'verbose_name': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemDificulty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сложность')),
                ('problemNumber', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер задачи')),
                ('problemSolutionImg', models.ImageField(blank=True, null=True, upload_to='exam/images/problemSolutions', verbose_name='Решение(картинка)')),
                ('problemSolutionText', models.TextField(blank=True, null=True, verbose_name='Решение(текст)')),
                ('commentRating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг комментария')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Комментарий',
            },
        ),
        migrations.CreateModel(
            name='examType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=20, verbose_name='Экзамен')),
                ('examTypeLogo', models.ImageField(blank=True, null=True, upload_to='exam/images/examTypeLogos', verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': 'Экзамены',
                'verbose_name': 'Экзамен',
            },
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemText', models.TextField(verbose_name='Условие задачи')),
                ('problemAverageDificulty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средняя сложность')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name_plural': 'Задачи',
                'verbose_name': 'Задача',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30, verbose_name='Предмет')),
                ('subjectLogo', models.ImageField(blank=True, null=True, upload_to='exam/images/subjectLogos', verbose_name='Иконка')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examType', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name_plural': 'Предметы',
                'verbose_name': 'Предмет',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.problem', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject', verbose_name='Предмет'),
        ),
    ]
