# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userID',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
    ]
